import type { FastifyInstance } from 'fastify';
import {
  listForecasts,
  getForecastBySku,
  listRecommendations,
  acceptRecommendation,
  dismissRecommendation,
  listAnomalies,
  resolveAnomaly,
  listModels,
  retrainModel,
  getMatchingScores,
  getSeasonalInsights,
} from './ai.handlers.js';
import {
  listForecastsSchema,
  getForecastBySkuSchema,
  listRecommendationsSchema,
  acceptRecommendationSchema,
  dismissRecommendationSchema,
  listAnomaliesSchema,
  resolveAnomalySchema,
  listModelsSchema,
  retrainModelSchema,
  matchingScoresSchema,
  seasonalInsightsSchema,
} from './ai.schemas.js';

export async function aiRoutes(fastify: FastifyInstance): Promise<void> {
  fastify.get('/ai/forecasts', {
    schema: {
      ...listForecastsSchema,
      tags: ['AI Intelligence'],
      summary: 'List demand forecasts',
      description: 'Returns demand forecasts with optional filters for skuId, locationId, and season. Forecasts are generated by the demand_forecast ML model and cover 12-week windows.',
    },
  }, listForecasts);

  fastify.get('/ai/forecasts/:skuId', {
    schema: {
      ...getForecastBySkuSchema,
      tags: ['AI Intelligence'],
      summary: 'Get detailed forecast for a SKU',
      description: 'Returns all forecast data points for a specific SKU including confidence intervals, summary statistics, and model version information.',
    },
  }, getForecastBySku);

  fastify.get('/ai/recommendations', {
    schema: {
      ...listRecommendationsSchema,
      tags: ['AI Intelligence'],
      summary: 'List AI recommendations',
      description: 'Returns active AI-generated recommendations. Filter by type (REORDER, TRANSFER, MARKDOWN, CANCEL_PO, EXPEDITE_PO) and status (PENDING, ACCEPTED, DISMISSED).',
    },
  }, listRecommendations);

  fastify.post('/ai/recommendations/:id/accept', {
    schema: {
      ...acceptRecommendationSchema,
      tags: ['AI Intelligence'],
      summary: 'Accept a recommendation',
      description: 'Marks a PENDING recommendation as ACCEPTED. Only recommendations in PENDING status can be accepted.',
    },
  }, acceptRecommendation);

  fastify.post('/ai/recommendations/:id/dismiss', {
    schema: {
      ...dismissRecommendationSchema,
      tags: ['AI Intelligence'],
      summary: 'Dismiss a recommendation',
      description: 'Dismisses a PENDING recommendation with an optional reason. The reason is stored in the recommendation reasoning for future model improvement.',
    },
  }, dismissRecommendation);

  fastify.get('/ai/anomalies', {
    schema: {
      ...listAnomaliesSchema,
      tags: ['AI Intelligence'],
      summary: 'List anomaly alerts',
      description: 'Returns anomaly alerts detected by the anomaly_detector model. Filter by type (DEMAND_SPIKE, DEMAND_DROP, SUPPLIER_DELAY, STOCK_DISCREPANCY, MARGIN_EROSION), severity (LOW, MEDIUM, HIGH, CRITICAL), and resolution status.',
    },
  }, listAnomalies);

  fastify.post('/ai/anomalies/:id/resolve', {
    schema: {
      ...resolveAnomalySchema,
      tags: ['AI Intelligence'],
      summary: 'Resolve an anomaly alert',
      description: 'Marks an unresolved anomaly alert as resolved. Cannot resolve an anomaly that is already resolved.',
    },
  }, resolveAnomaly);

  fastify.get('/ai/models', {
    schema: {
      ...listModelsSchema,
      tags: ['AI Intelligence'],
      summary: 'List model registry',
      description: 'Returns all registered ML models with their versions, status, performance metrics, and training metadata.',
    },
  }, listModels);

  fastify.post('/ai/models/:name/retrain', {
    schema: {
      ...retrainModelSchema,
      tags: ['AI Intelligence'],
      summary: 'Trigger model retraining',
      description: 'Initiates a manual retraining for the specified model. Creates a new version entry in TRAINING status. This is a mock operation that immediately creates the training record.',
    },
  }, retrainModel);

  fastify.get('/ai/matching/scores', {
    schema: {
      ...matchingScoresSchema,
      tags: ['AI Intelligence'],
      summary: 'Get neural match scores',
      description: 'Returns match scores and factor breakdowns for current PROPOSED and AUTO_CONFIRMED SO-PO matches. Scores are generated by the match_scorer neural network.',
    },
  }, getMatchingScores);

  fastify.get('/ai/insights/season/:season/:year', {
    schema: {
      ...seasonalInsightsSchema,
      tags: ['AI Intelligence'],
      summary: 'Get seasonal AI insights',
      description: 'Returns a comprehensive AI insights summary for a given season and year, including demand forecasts, recommendation statistics, anomaly breakdown, matching performance, and historical sales context.',
    },
  }, getSeasonalInsights);
}
